const fileofbody= {
products:  [
  
    {
      _id: '1',
      name: 'K/mhret Furniture',
      category: 'bed',
      image: '/images/p1.jpg',
      price: 7120,
      countInStock: 10,
      brand: 'New',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    }, {
      _id: '2',
      name: 'Nbm Furniture',
      category: 'chair',
      image: '/images/p7.jpg',
      price: 7120,
      countInStock: 10,
      brand: 'New',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'K/mhret Furniture',
      category: 'bed',
      image: '/images/p1.jpg',
      price: 7120,
      countInStock: 10,
      brand: 'New',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    }, {
      _id: '4',
      name: 'Nbm Furniture',
      category: 'chair',
      image: '/images/p7.jpg',
      price: 7120,
      countInStock: 10,
      brand: 'New',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'K/mhret Furniture',
      category: 'bed',
      image: '/images/p1.jpg',
      price: 7120,
      countInStock: 10,
      brand: 'New',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    }, {
      _id: '5',
      name: 'Nbm Furniture',
      category: 'chair',
      image: '/images/p7.jpg',
      price: 7120,
      countInStock: 10,
      brand: 'New',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ]
}
export default fileofbody;